<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <link rel="canonical" href="https://knocscore.com/privacy">
    <meta name="robots" content="noindex, nofollow">
    <#include "common/icon_block.ftl">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="title" content="Privacy">
    <#-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://knocscore.com/privacy">
    <meta property="og:title" content="Privacy">
    <!-- styles -->
    <#include "common/styles_block_infopg.ftl">
    <!-- javascript -->
    <link href="/app/style/animate-style.css" rel="stylesheet" type="text/css">
    <!-- javascript -->
    <#-- custom javascript -->
    <script src="/app/javascript/non-index.js"></script>
</head>
<body>
<section>
    <!-- Modal Sign up -->
    <#include "modals/signup_modal.ftl">
    <#-- Thank you MODAL -->
    <#include "modals/stripe_thankyou_modal.ftl">
    <#-- nav -->
    <#include "section/non-index-nav.ftl">
</section>
<br class="clearfloat">
<div class="sr-root">
    <div class="container" >
        <div class="row">
            <div class="col-md-12">
                <br>
                <br>
                <br>
                <h1>Privacy Policy</h1>
                <br>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 bg-light info-text">
                <article class="container-lg" itemprop="text">
                    <p>At KnocScore we believe privacy is an intrinsic right. However, in order to operate and provide you services, there is certain information that we must collect. Our system operates on Data, this is the nature of software as a service companies.
                        Here is our fundamental policy outline:</p>
                    <ul dir="auto">
                        <li>Bottom line upfront. We do not sell your information collected for use by KnocScore, nor do we share it with data brokers. Full-Stop.</li>
                        <li>We make it easy for you to maintain your privacy or show off your capabilities either publicly or to a select few.</li>
                        <li>We are thoughtful about the personal information we ask you to provide and the personal information that we collect about you through and for the operation of our services.</li>
                        <li>We store personal information for only as long as we have a reason to keep it. This means that if you request to delete your information, services that you have worked hard to create, will no longer be available. Once it is gone. We have no means to recover it.</li>
                        <li>We aim to make it as simple as possible for you to share and unshare your information publicly (E.G. indexed by search engines) or to a select few (Through the use of a link).</li>
                        <li>We intend to help protect you from overreaching government demands for your personal information through the use of encryption and limited access.</li>
                        <li>We aim for full transparency on how we gather, use, and share your personal information.</li>
                        <li><strong>NOTE:</strong>Use of our website, with your consent, does use Google Analytics and Tags to track our websites use. This is critical information so we may improve our website's use, and understand our visitors. Importantly, we do not share KnocScore data with Google nor anyone else.</li>
                    </ul>
                    <p dir="auto">Below is our Privacy Policy, which incorporates and clarifies these principles.</p>
                    <h3 dir="auto"><a id="user-content-who-we-are-and-what-this-policy-covers" class="anchor" aria-hidden="true" href="#who-we-are-and-what-this-policy-covers"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Who We Are and What This Policy Covers</h3>
                    <p dir="auto">Hey there! We are the folks behind screen who designed and created a small company to provide education, learning services, income, and job opportunities through a novel connection of traditionally disparate entities. In other words, provide a unique service that does more to help our users learn, make money, and get jobs. This Privacy Policy applies to information that we collect under the following use or situations:</p>
                    <ul dir="auto">
                        <li>The KnocScore.com and TopScholars.co websites;</li>
                        <li>Our desktop and when available mobile applications;</li>
                        <li>Current and future ecosystems;</li>
                        <li>Throughout this Privacy Policy we’ll refer to our websites, applications, and other products and services collectively as "Services".</li>
                    </ul>
                    <h3 dir="auto"><a id="user-content-creative-commons-sharealike-license" class="anchor" aria-hidden="true" href="#creative-commons-sharealike-license"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Creative Commons Sharealike License</h3>
                    <p dir="auto">This Privacy Policy is forked from Automattic under a <a href="https://creativecommons.org/licenses/by-sa/4.0/" rel="nofollow">Creative Commons Sharealike</a> license. Their Privacy Policy and other legal documents are available at <a href="https://github.com/Automattic/legalmattic">Automattic GitHub</a>. Our privacy policy is available at <a href="https://github.com/runnermann/legalmattic/blob/master/Privacy-Policy.md">KnoC Inc. GitHub</a>.</p>
<#--                    <h3 dir="auto"><a id="user-content-information-flashmonkey-collects" class="anchor" aria-hidden="true" href="#information-flashmonkey-collects"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Information FlashMonkey Collects</h3>-->
                    <p dir="auto">We collect information about you when we have a reason to do so — for example, to provide our Services, to communicate with you, or to make our Services better. We collect this information from three sources: if and when you provide information to us, automatically through operating our Services, and from outside sources. Let’s go over the information that we collect.</p>
                    <h4 dir="auto"><a id="user-content-information-you-provide-to-us" class="anchor" aria-hidden="true" href="#information-you-provide-to-us"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Information You Provide to Us</em></h4>
                    <p dir="auto">Our services fundamentally require the transfer of information from you and the machines you use to interact with us. Thus, it is probably no surprise that we collect the information that you provide to us directly and indirectly.</p>
                    <ul dir="auto">
                        <li><strong>Basic account information:</strong> We ask for basic information from you in order to set up your account. For example, we require individuals who sign up for a KnocScore account to provide an email address and password, along with a username or name.</li>
                        <li><strong>Users shared profile information:</strong> If you use the ecosystem to sell or distribute learning materials, we collect the information that you provide for your profile. For example, your avatar name is part of that system profile, along with any other information you put into your shared profile, like a photo or an "About Me" description, graduation date and learning institute. Your shared profile information is shared in our system but should be considered public. Please keep that in mind when deciding what information you would like to include.</li>
<#--                        <li><strong>Payment and contact information:</strong> There are various ways in which you may provide us payment information and associated contact information. For example, if you buy learning materials or a license plan, you’ll provide additional personal and payment information like your name, credit card information, and contact information. We also keep a record of the purchases you’ve made. If you use the ecosystem to earn an income, you’ll have to create a KnocScore account and an account with our payment services partner, currently Stripe. Please note that Stripe provides financial services and shares only the limited information needed for transactions.</li>-->
<#--                        <li><strong>Jobs Profile:</strong> An important advantage of the TopScholars Platform, if you volunteer to share your learning analytics and earnings with recruiters, your profile image, and name is collected and shared with the entities that you provide a link to. For example, if you have created learning materials, studied them, and made them available in the ecosystem, these analytics help to tell recriuters and future employers your work ethics, the domain of knowledge you've learned, and the crowd sourced value others have paid for the knowledge you've created and studied.</li>-->
                        <li><strong>Content information:</strong> The content your provide, images, text, video, sound and or software by the nature of our services is collected and stored. You might provide information about yourself in the content of learning materials. We recommend that when you do so you limit it solely to the needed context. E.G. do not share current location information and never share financial information.</li>
                        <li><strong>Communications with us (hey there!):</strong> You may also provide us with information when you respond to surveys, communicate with our Engineers about a support question, post a question in a public forums, or sign up for a newsletter like the one we spam you with. If you communicate with us via email, phone, or at buy us coffee at the local coffee shop (please), or otherwise, we store a copy of our communications (including any call recordings as permitted by applicable law) We don't collect information you give to us when you buy us coffee at the local coffee shop, but we may take notes if you give us comments.</li>
                    </ul>
                    <h4 dir="auto"><a id="user-content-information-we-collect-automatically" class="anchor" aria-hidden="true" href="#information-we-collect-automatically"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Information We Collect Automatically</em></h4>
                    <p dir="auto">We also collect some information programmatically:</p>
                    <ul dir="auto">
                        <li><strong>Log information:</strong> Like most online service providers, we collect information that web browsers, mobile devices, and servers typically make available, including the browser type, IP address, unique device identifiers, language preference, referring site, the date and time of access, operating system, and mobile network information. We collect log information when you use our Services — for example, when you download our app, were you able to open it. Or how long did you spend while creating learning materials, and how long did you spend studying them.</li>
                        <li><strong>Finance Transactional information:</strong> When you make a purchase through our Services, we collect information about the transaction, such as product details, purchase price, and the date and location of the transaction. This includes when you purchase learning materials.</li>
                        <li></li>
                        <li><strong>Usage information:</strong> We collect information about your usage of our Services. For example, we collect information about the actions you take in the application.</li>
                        <li><strong>Learning Analytics:</strong> The services we provide require us to collect information on your use of our application both during creation and studying or interacting with the learning materials. This includes the amount of time spent studying, the amount of time spent creating, the types of learning materials, the domain of knowledge of the learning materials, the number of questions that were answered and the number of times they were viewed. We may track when and if the content was edited and may associate it with you and other users who are using versions of the learning materials you are studying. We consider this to be private information and we ambiguate and encrypt association of your information with your name.</li>
                        <li><strong>Location information:</strong> We may determine the approximate location of your device from your IP address. We collect and use this information to, for example, calculate how many people visit our Services from certain geographic regions. If you provide photos to KnocScore, they may contain precise location information when taken from a mobile device, and in such cases has been shared with KnocScore or TopScholars.</li>
                        <li><strong>Stored information:</strong> Our app accesses information stored on your device. We access this stored information through your device operating system’s permissions. For example, if you give us permission to access the photographs on your device’s camera roll, our Services may access the photos stored on your device when you upload images or video for learning materials.</li>
                        <li><strong>Interactions with other users:</strong> We collect some information about your interactions with other users learning materials such as your ratings of a deck so that we may transparently show if learning materials are accurate  and high quality.</li>
                        <li><strong>Information from cookies &amp; other technologies:</strong> A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. Pixel tags (also called web beacons) are small blocks of code placed on websites and emails. KnoC Inc. uses cookies and other technologies like pixel tags to help us identify and track visitors, usage, and access preferences for our Services, as well as track and understand email campaign effectiveness. For more information about our use of cookies and other technologies for tracking.</li>
                        <li><Strong>Google Analytics and Google Tags</Strong>Building a business in today's world is hard. We've struggled to avoid the use of Google Analytics and found it near impossible. We do not store information collected by Google, but Google Analytics is used to collect website data. We need this data to understand how you use our website so we can improve its design and functionality. We also need the data to get the most out of our marketing campaigns.
                            With your consent when you agree to our cookie policy, Google Analytics will process and collect your personal data (cookies, tags, and IP address) to give us valuable information. Google Analytics will transfer your data to the United States and store it for 6 months. To learn more about Google's data transfer policies, <a href="https://policies.google.com/technologies/partner-sites">click here.</a>
                            Please note, we do not store information collected by Google</li>
                    </ul>
                    <h4 dir="auto"><a id="user-content-information-we-collect-from-other-sources" class="anchor" aria-hidden="true" href="#information-we-collect-from-other-sources"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Information We Collect from Other Sources</em></h4>
                    <p dir="auto">We may also get information about you from other sources. For example:</p>
                    <ul dir="auto">
                        <li><strong>Social Sharing Services:</strong> If you connect your website or account to a social media service (like Twitter) through our Publicize feature, we’ll receive information from that service (e.g., your username, basic profile information, friends list) via the authorization procedures for that service.</li>
                        <li><strong>Financial Account Info:</strong> If you use the ecosystem, we’ll receive information relating to your Stripe account, such as your email address and phone number and payment information from Stripe.</li>
                    </ul>
                    <p dir="auto">The information we receive depends on which services you use or authorize and what options are available.</p>
                    <p dir="auto"><del>Third-party services, if we opt to use them, may also give us information like mailing addresses for individuals who are not yet our users (but we hope will be!). We use this information for marketing purposes like postcards and other mailers advertising our Services.</del></p>
                    <h3 dir="auto"><a id="user-content-how-and-why-we-use-information" class="anchor" aria-hidden="true" href="#how-and-why-we-use-information"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>How and Why We Use Information</h3>
                    <h4 dir="auto"><a id="user-content-purposes-for-using-information" class="anchor" aria-hidden="true" href="#purposes-for-using-information"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Purposes for Using Information</em></h4>
                    <p dir="auto">We use information about you for the purposes listed below:</p>
                    <ul dir="auto">
                        <li><strong>To provide our Services.</strong> For example, to set up and maintain your account, host your website, backup and restore your website, provide customer service, process payments and orders, and verify user information.</li>
                        <li><strong>To ensure quality, maintain safety, and improve our Services.</strong> For example, by providing automatic upgrades and new versions of our Services. Or, for example, by monitoring and analyzing how users interact with our Services so we can create new features that we think our users will enjoy and that will help them create and manage websites more efficiently or make our Services easier to use.</li>
                        <li><strong>To market our Services and measure, gauge, and improve the effectiveness of our marketing.</strong> For example, by targeting our marketing messages to groups of our users (like those who have a particular plan with us or have been users for a certain length of time), advertising our Services, analyzing the results of our marketing campaigns (like how many people purchased a paid plan after receiving a marketing message), and understanding and forecasting user retention.</li>
                        <li><strong>To protect our Services, our users, and the public.</strong> For example, by detecting security incidents; detecting and protecting against malicious, deceptive, fraudulent, or illegal activity; fighting spam; complying with our legal obligations; and protecting the rights and property of KnoC Inc. and others, which may result in us, for example, declining a transaction or terminating Services.</li>
                        <li><strong>To fix problems with our Services.</strong> For example, by monitoring, debugging, repairing, and preventing issues.</li>
                        <li><strong>To customize the user experience.</strong> For example, to personalize your experience by serving you relevant notifications and advertisements for our Services, recommending content through our Reader post suggestions, and providing new essays and stories through Longreads for your reading pleasure.</li>
                        <li><strong>To communicate with you.</strong> For example, by emailing you to ask for your feedback, share tips for getting the most out of our products, or keep you up to date on KnoC Inc.; texting you to verify your payment; or calling you to share offers and promotions that we think will be of interest to you. If you don’t want to hear from us, you can opt out of marketing communications at any time. (If you opt out, we’ll still send you important updates relating to your account.)</li>
                        <li><strong>To recruit and hire new employees and interns.</strong> For example, by evaluating job applicants and communicating with them.</li>
                    </ul>
                    <h4 dir="auto"><a id="user-content-legal-bases-for-collecting-and-using-information" class="anchor" aria-hidden="true" href="#legal-bases-for-collecting-and-using-information"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Legal Bases for Collecting and Using Information</em></h4>
                    <p dir="auto">At this time we are not expecting users from the EU and some services are not currently intended for EU use. However, for those in the European Union about our legal grounds for processing information about you under EU data protection laws, which is that our use of your information is based on the grounds that: (1) The use is necessary in order to provide the services to you and other users like you and necessary to fulfill our commitments to you under the our agreements with you and as necessary to administer your account. — for example, in order to protect and enable your access to your content on your devices or pay you for a learning materials another user has purchased; or (2) The use is necessary for compliance with a legal obligation; or (3) The use is necessary in order to protect your vital interests or those of another person; or (4) We have a legitimate interest in using your information — for example, to provide and update our Services; to improve our Services so that we can offer you an even better user experience; to safeguard our Services; to communicate with you; to measure, gauge, and improve the effectiveness of our advertising; and to understand our user retention and attrition; to monitor and prevent any problems with our Services; and to personalize your experience; or (5) You have given us your consent — for example before we place certain cookies on your device and access and analyze them later on.</p>
                    <h3 dir="auto"><a id="user-content-sharing-information" class="anchor" aria-hidden="true" href="#sharing-information"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Sharing Information</h3>
                    <h4 dir="auto"><a id="user-content-how-we-share-information" class="anchor" aria-hidden="true" href="#how-we-share-information"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>How We Share Information</em></h4>
                    <p dir="auto">When you've selected to do so, we share information you've provided to KnocScore and or TopScholars</p>
                    <ul dir="auto">
                        <li><strong>With our Payment System Partners:</strong> We share the information that is necessary for financial transaction with Stripe in order to process payments that you've made for a purchase, or in order to pay you from someone else's purchase.**</li>
                        <li><strong>With other users:</strong> When you select to sell and/or share your study materials in the ecosystem. Certain information is shared with other users so that there is transparency in who created the materials, what your relation is to the materials such as the degree you are studying for, and background information that will provide credibility to other users who are may purchase your decks. This includes for example your avatar name, and your avatar image. Users may become familiar with your avatar name and image and search for materials using these.</li>
                        <li><strong>With recruiters:</strong> When you select to make your analytics available by through the use of a code, your information is shared to anyone that has the code. In this case the learning analytics that you've worked for in the TopScholars App, and have selected to make available along with your name and image is available information. You may share this information in social media such as LinkedIn, and Facebook.</li>
                        <li><strong>With the public:</strong> When you select to make your decks or your analytics available to the public. In this case the information that you've selected is available to the public and may appear in SERPS, it may also appear in social media when your information is shared with them. In the case of decks your avatar and your avatar name is available to the public. In the case of analytics your name and image is associated with the information.</li>
                        <li><strong>Legal and regulatory requirements:</strong> We may disclose information about you in response to a subpoena, court order, or other governmental request.</li>
                        <li><strong>To protect rights, property, and others:</strong> We may disclose information about you when we believe in good faith that disclosure is reasonably necessary to protect the property or rights of KnoC Inc., third parties, or the public at large. For example, if we have a good faith belief that there is an imminent danger of death or serious physical injury, we may disclose information without delay.</li>
                        <li><strong>Business transfers:</strong> In connection with any merger, sale of company assets, or acquisition of all or a portion of our business by another company, or in the unlikely event that KnoC Inc. goes out of business or enters bankruptcy, user information would likely be one of the assets that is transferred or acquired by a third party. If any of these events were to happen, this Privacy Policy would continue to apply to your information and the party receiving your information may continue to use your information, but only consistent with this Privacy Policy.</li>
                        <li><strong>Aggregated or de-identified information:</strong> We may share information that has been aggregated or de-identified, so that it can no longer reasonably be used to identify you. For example, to show to investors or for research purposes.</li>
                    </ul>
                    <p dir="auto">We have a long-standing policy that we do not sell our users' data to data-brokers. We don't give it away to email companies such as MailMonkey etc... to email you. We are not a data broker. However, we may share your information that you've chosen to make public. We may share your information that you chose to share with individuals or firms for the purposes of job hunting or recognition for your accomplishments.
                        We may show ads in some locations in the app or on a website in order to offset costs and provide a lower cost product to our users. Under the California law, the California Consumer Privacy Act ("CCPA"), some personalized advertising you see online and on our services might be considered a "sale" even though we don't share information that identifies you personally, like your name or email address, as part of our advertising program.</p>
                    <h4 dir="auto"><a id="user-content-information-shared-publicly" class="anchor" aria-hidden="true" href="#information-shared-publicly"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Information Shared Publicly</em></h4>
                    <p dir="auto">Information that you choose to make public is — you guessed it — disclosed publicly. As mentioned previously, that means information like your name and profile image along with your analytics and earnings, or your avatar image and avatar name along with the learning materials information are available in social media posts you may make, are available and we hope they get a lot of views!</p>
                    <h3 dir="auto"><a id="user-content-how-long-we-keep-information" class="anchor" aria-hidden="true" href="#how-long-we-keep-information"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>How Long We Keep Information</h3>
                    <p dir="auto">We generally discard information about you when it’s no longer needed for the purposes for which we collect and use it — described in the section above on How and Why We Use Information — and we’re not legally required to keep it. For example, we keep web server logs that record information about visitors to the KnocScore website, like the visitor’s IP address, browser type, and operating system, for approximately 365 days. We retain the logs for this period of time in order to, among other things, analyze traffic to KnocScore’s websites and investigate issues if something goes wrong.</p>
                    <h3 dir="auto"><a id="user-content-choices" class="anchor" aria-hidden="true" href="#choices"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Choices</h3>
                    <p dir="auto">You have several choices available when it comes to information about you:</p>
                    <ul dir="auto">
                        <li><strong>Limit the information that you provide:</strong> If you have an account with us, you can choose not to provide the optional account information, profile information, and transaction and billing information. Please keep in mind that if you do not provide this information, certain features of our Services such as showing analytics to employers and the ability to earn from your learning materials will not be accessible.</li>
                        <li><strong>Limit access to information on your mobile device:</strong> Your mobile device operating system should provide you with the option to discontinue our ability to collect stored information or location information.</li>
                        <li><strong>Set your browser to reject cookies:</strong> In general, KnocScore does not use cookies to store information in browsers. Additionally, at this time, KnoC Inc. does not respond to "do not track" signals and there is no standard provided for this to work. However, you may select to reject cookies by your browser.</li>
                        <li><strong>Close your account:</strong> While we’d be very sad to see you go, you can close your account if you no longer want to use our Services. However, in so doing, and if you chose to delete your information, you will stop recieving payments from learning materials you've set up to sell. We will delete your learning materials if you so chose to request this, however anyone who has purchased your learning materials will continue to have rights to it. If you are an original creator, your future profits will be sent either to KnoC Inc or to the next child distributor.</li>
                    </ul>
                    <h3 dir="auto"><a id="user-content-your-rights" class="anchor" aria-hidden="true" href="#your-rights"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Your Rights</h3>
                    <p dir="auto">If you are located in certain parts of the world, including California and countries that fall under the scope of the European General Data Protection Regulation (aka the "GDPR"), you may have certain rights regarding your personal information, like the right to request access to or deletion of your data.</p>
                    <h4 dir="auto"><a id="user-content-european-general-data-protection-regulation-gdpr" class="anchor" aria-hidden="true" href="#european-general-data-protection-regulation-gdpr"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>European General Data Protection Regulation (GDPR)</em></h4>
                    <p dir="auto">If you are located in a country that falls under the scope of the GDPR, data protection laws give you certain rights with respect to your personal data, subject to any exemptions provided by the law, including the rights to:</p>
                    <ul dir="auto">
                        <li>Request access to your personal data;</li>
                        <li>Request correction or deletion of your personal data;</li>
                        <li>Object to our use and processing of your personal data;</li>
                        <li>Request that we limit our use and processing of your personal data; and</li>
                        <li>Request portability of your personal data.</li>
                    </ul>
                    <p dir="auto">You also have the right to make a complaint to a government supervisory authority.</p>
                    <h4 dir="auto"><a id="user-content-california-consumer-privacy-act-ccpa" class="anchor" aria-hidden="true" href="#california-consumer-privacy-act-ccpa"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>California Consumer Privacy Act (CCPA)</em></h4>
                    <p dir="auto">As of the time of this writing, KnocScore does not fall into the catagory that The California Consumer Privacy Act ("CCPA") is required/ That being said, we will work to ensure we comply to your rights and your wishes weather you live in CA or outside of it. The follwing is information that we follow according to the CCPA also requires us to provide a list of the "categories" of personal information we collect, as that term is defined in the law, so, here it is. In the last 12 months, we collected the following categories of personal information from California residents, depending on the Services used:</p>
                    <ul dir="auto">
                        <li>
                            <p dir="auto">Identifiers (like your name, contact information, and device and online identifiers);</p>
                        </li>
                        <li>
                            <p dir="auto">Commercial information (your billing information and purchase history, for example);</p>
                        </li>
                        <li>
                            <p dir="auto">Characteristics protected by law (for example, you might provide your gender as part of a research survey for us);</p>
                        </li>
                        <li>
                            <p dir="auto">Internet or other electronic network activity information (such as your usage of our Services, like the actions you take in our app or website);</p>
                        </li>
                        <li>
                            <p dir="auto">Geolocation data (such as your location based on your IP address);</p>
                        </li>
                        <li>
                            <p dir="auto">Audio, electronic, visual or similar information (such as your profile picture, if you uploaded one);</p>
                        </li>
                        <li>
                            <p dir="auto">Request to know the categories of personal information we collect, the categories of business or commercial purpose for collecting and using it, the categories of sources from which the information came, the categories of third parties we share it with, and the specific pieces of information we collect about you;</p>
                        </li>
                        <li>
                            <p dir="auto">Request deletion of personal information we collect or maintain;</p>
                        </li>
                        <li>
                            <p dir="auto">Opt out of any sale of personal information; and</p>
                        </li>
                        <li>
                            <p dir="auto">Not receive discriminatory treatment for exercising your rights under the CCPA.</p>
                        </li>
                    </ul>
                    <h4 dir="auto"><a id="user-content-contacting-us-about-these-rights" class="anchor" aria-hidden="true" href="#contacting-us-about-these-rights"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a><em>Contacting Us About These Rights</em></h4>
                    <p dir="auto">You can usually access, correct, or delete your personal data using your profile in our app. If you contact us about one of your rights under this section, we’ll need to verify that you are the right person before we disclose or delete anything. For example, if you are a user, we will need you to contact us from the email address associated with your account. You can also designate an authorized agent to make a request on your behalf by giving us written authorization. We will require you to verify your identity with us.</p>
                    <h3 dir="auto"><a id="user-content-how-to-reach-us" class="anchor" aria-hidden="true" href="#how-to-reach-us"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>How to Reach Us</h3>
                    <p dir="auto">If you would like to contact us to delete your information send an email from the account email to <a href="mailto:member-services@knocscore.com">member-services@knocscore.com</a></p>
                    <h3 dir="auto"><a id="user-content-other-things-you-should-know-please-keep-reading-after-all-someone-spent-time-writing-this" class="anchor" aria-hidden="true" href="#other-things-you-should-know-please-keep-reading-after-all-someone-spent-time-writing-this"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Other Things You Should Know (Please keep reading. After all, someone spent time writing this)</h3>
                    <h4 dir="auto"><a id="user-content-_transferring-information_and-information_storage" class="anchor" aria-hidden="true" href="#_transferring-information_and-information_storage"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>_Transferring Information_and Information_Storage</h4>
                    <p dir="auto">The information that is collected including learning materials you create, analytics, and the personal information we collect is stored in the United States. If you live outside the US, you are not intended to use our platform and some features will only select US locations, at least until a future time. That being said, you may view us and use our application. Your information is transferred from your location to the US.</p>
                    <h3 dir="auto"><a id="user-content-privacy-policy-changes" class="anchor" aria-hidden="true" href="#privacy-policy-changes"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Privacy Policy Changes</h3>
                    <p dir="auto">Although most changes are likely to be minor, KnoC Inc. may change its Privacy Policy from time to time. KnoC Inc. encourages visitors to frequently check this page for any changes to its Privacy Policy. If we make changes, we will notify you by revising the change log below, and, in some cases, we may provide additional notice (like adding a statement to our homepage or the KnocScore.com](<a href="https://knocscore.com/" rel="nofollow">https://knocscore.com/</a>) or sending you a notification through email or your dashboard). Your further use of the Services after a change to our Privacy Policy will be subject to the updated policy.</p>
                    <h3 dir="auto"><a id="user-content-change-log" class="anchor" aria-hidden="true" href="#change-log"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>Change log</h3>
                    <ul dir="auto">
                        <li><em>March 6, 2024</em>: First release.</li>
                    </ul>
                </article>
            </div>
        </div>
    </div>
</div>
<!-- footer -->
<#include "new_footer.ftl">
<#include "common/closeout_scripts.ftl">
<#--<script async src="https://js.stripe.com/v3/buy-button.js"></script>-->
</body>
</html>