/*
 *  Copyright (c) 2017 Red Hat, Inc. and/or its affiliates.
 *  Copyright (c) 2017 INSA Lyon, CITI Laboratory.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Modified for FlashMonkey Application. The entire enum has been modified.
 */

package com.knocscore.database;


enum SqlQuery {
    DB_ROLLBACK,
    SELECT_PREKICK_BACKERS,
    FETCH_KSCORE_PREKICK_STATS,
    INSERT_KSCORE_DONATE_TRX,
    ALL_USERS,
    CREATE_USERS_TABLE,
    USER_EXISTS,
    GET_USER_BY_EMAIL,
    CREATE_USER,
    CREATE_USER_FMAPPREQ,
    CREATE_KNOC_USER,
    FINALIZE_NEW_USER,
    SAVE_USER,
    ALL_USERS_DATA,
    GET_USER_BY_UUID,
    ALL_USERS_DECKS,
    DECKS_BY_SUBJECT,
    SET_CODE,
    UPDATE_PW,
    UPDATE_STRIPE_ID,
    SUBSCRIPT_START,
    SUBSCRIPT_CANCEL,
    SUBSCRIPT_CANCEL_ONID,
    UPDATE_SUBSCRIPTION,
    UPDATE_SUBSCRIPTION_ONID,
    UPDATE_SUBSCRIPTION_TRIALONID,
    UPDATE_STUDENT,
    UPDATE_BIO,
    UPSERT_ATHLETE,
    UPSERT_ATHLETE_IMAGE,
    UPSERT_ED_GENERAL,
    UPSERT_MIL_SERVICE,
    UPSERT_MIL_IMAGE,

    UPSERT_USER_DECKSTATSAMOUNT,
    QR_FETCH_DECK_NAME_PRICE,
    QR_FETCH_CAMPAIGN,
    FETCH_ACCT_NO,
    FETCH_ALL_JOBS,
    FETCH_CHILDDECK_EXISTS,
    FETCH_CODE,
    FETCH_DECK_PUR_DETAILS,
    FETCH_HASPURCHASED,
    FETCH_JOB_BY_ID,
    FETCH_MEMBER_STATUS,
    FETCH_PREDECESSOR_USER,
    FETCH_STRIPE_ID,
    FETCH_STUDENT,
    FETCH_SUBSCRIPT_ID,
    FETCH_TEAM,
    FETCH_USER_HASH,
    FETCH_USER_STATS,
    FETCH_STATS_ENTITY,
    FETCH_STATS_POS,
    FETCH_STATS_PROJECTS,
    FETCH_STATS_ACHIEVEMENT,
    FETCH_STATS_ATHLETICS,
    FETCH_STATS_PEOPLE,
    FETCH_STATS_KNOWLEDGE,
    FETCH_MEMBERS_LIST,

    FETCH_BULK_EMAIL_REQS,
    FETCH_EMAILS_OTHER,
    FETCH_EMAILS_DIFF,
    FETCH_VIDEOCHAT_ATTENDEE,
    FETCH_VIDEOCHAT_MEETING,
    FETCH_VIDEOCHAT_PCODE,
    FETCH_ALL_BLOGS,
    FETCH_BLOG_ROWS,
    FETCH_BLOG_BY_ID,
    FETCH_BLOG_REFS,

    INSERT_POR_EMPLOYER,
    INSERT_INDUSTRY_DATA,
    INSERT_APP_REQ,
    INSERT_CAMPAIGN_KEYCLICK,
    INSERT_VISITOR,
    INSERT_MEMBERSHIP_FEE,
    INSERT_NOTE_PERSON,
    INSERT_NOTE_SYSTEM,
    INSERT_PAYMENT_RECIEVED,
    INSERT_PREDECESSORCHAIN,
    INSERT_PURCHASED_CHILDDECK,
    INSERT_TRANSACTION,
    INSERT_EMAIL_PREKICK,
    UPSERT_EMAIL_BOUNCED,
    UPSERT_EMAIL_OPENED,
    UPSERT_EMAIL_COMPLAINT,
    UPSERT_EMAIL_OPTOUT,
    UPSERT_USER_CODE,
    DELETE_USER,
    DELETE_TEST_MONKEY,
    DELETE_PREDECESSOR_MONKEY,
    INSERT_VIDEOCHAT_HOST,
    INSERT_VIDEOCHAT_ATTENDEE
}
